makersquare/lucere

config/routes.js
=> fixed comma in line 37 of routes

bower.json
add angular-route to bower.json
=> add angular-route to bower.json

assets/js/app.js, assets/js/controllers/lesson_ctrl.js, assets/js/controllers/library_ctrl.js, assets/js/controllers/module_ctrl.js, assets/js/controllers/team_ctrl.js, assets/js/services/module_service.js, assets/js/templates/lesson_template.html, assets/js/templates/library_template.html, assets/js/templates/module_template.html, assets/js/templates/team_template.html, views/layout.ejs
Add basic routing + template + controller
=> Module angular

assets/js/controllers/lesson_ctrl.js, assets/js/directives/admin_lesson_directive.js, assets/js/services/lesson_service.js, assets/js/templates/admin_lesson_template.html, assets/js/templates/lesson_template.html, views/layout.ejs
Successfully implemented lesson directive. Editor can query lessons, load them into text field, and save new information to the database. UPDATED: 2/2/15 1:10pm
=> Lesson directive

assets/js/directives/admin_lesson_directive.js, assets/js/directives/student_lesson_directive.js, assets/js/templates/lesson_template.html, assets/js/templates/student_lesson_template.html, config/bootstrap.js, views/layout.ejs
Create student lesson directive, a read only version of the admin lesson directive.
=> create student lesson directive

assets/js/controllers/library_ctrl.js, assets/js/directives/library_directive.js, assets/js/services/library.js, assets/js/templates/admin_library_template.html, assets/js/templates/library_template.html, views/layout.ejs
Create view for library, can create new modules
=> Library angular

assets/js/app.js, tasks/pipeline.js, views/layout.ejs
-Adds to pipeline
-Inject as dependency to our 'Lucere' module.
=> Adds drag_and_drop library

assets/js/app.js, tasks/pipeline.js, views/layout.ejs
-Add drag-and-drop to pipeline
-Inject dndLists as dependency to module
=> Drag and drop

assets/js/controllers/header_ctrl.js, assets/js/controllers/sidebar_ctrl.js, views/layout.ejs
Add main layout view skelton to hold primary Angular directives.
=> Main view skeleton

assets/js/app.js, assets/js/templates/login_template.html
=> Add login page.

api/controllers/UserController.js, assets/js/app.js, assets/js/controllers/user_ctrl.js, assets/js/services/auth_service.js, assets/js/services/user_service.js, assets/js/templates/user_profile_template.html, config/bootstrap.js, config/routes.js, views/layout.ejs
User profile view should be tested when viewing own profile (on which edit options should be present) and on the profile page of some other user (since you should not be able to edit another user's profile info).
/#/user/:id
=> Add user profile view with AuthService for retrieving current user.

assets/js/controllers/team_ctrl.js, assets/js/services/team_service.js, assets/js/templates/team_template.html, views/layout.ejs
/#/team/:id
View differs depending on whether the current user (you) are an admin of the team in question or not. 
View also differs if you're looking at the core library (id = 1).
=> Add team views.

assets/js/app.js, assets/js/controllers/user_creation_ctrl.js, assets/js/templates/user_create_template.html, views/layout.ejs
Add form for creating new users.
=> Add New User

assets/js/templates/team_template.html, views/layout.ejs
Team view now links to angular routes of user profile pages
=> fix hrefs on team_template

assets/js/controllers/user_ctrl.js
Add a cancel button to the edit profile page. On your own profile page, you may click edit and then choose to proceed with your changes or use the exciting new cancel button to discard your changes.
=> add cancel button to edit user profile page

api/controllers/UserController.js
To login, you can still go to /#/login and click the login button, or you can go to /user/auth. After hitting one of these routes, if login is successful, you will now be redirected to your profile page.
=> Redirect after login

assets/js/controllers/user_ctrl.js, assets/js/templates/team_template.html, assets/js/templates/user_profile_template.html, views/layout.ejs
From your profile page (/#/user/:id -- get your id by looking for yourself in the bootstrap file or by looking for yourself in /user) you should see an "Edit" button. After you click this button, you should see a form filled with your profile info. 
Original form functionality should remain: 
If you edit this info and hit cancel, the form should disappear and your original data should reappear.
If you edit this info and hit submit, the form should disappear and your new values should show up. If you go to the /user/:your-id, you should now see your updated data.
Additional form functionality: validation. Submit button should be disabled when required fields are empty.
Validation has also been added to the form at the top of all team pages: /#/team/:teamId.
To test the last bit of …
=> Form validation

assets/js/directives/admin_lesson_directive.js, assets/js/directives/student_lesson_directive.js
Removing a couple unnecessary console.logs that were missed during prior code reviews.
=> Removing unnecessary console.logs

assets/js/directives/student_lesson_directive.js, assets/js/directives/student_sidebar_directive.js, assets/js/templates/sidebar_template.html, assets/js/templates/student_sidebar_template.html, views/layout.ejs
Sidebar directive for students to display all modules and lessons within their library.
=> Add student sidebar directive components.

assets/js/controllers/team_ctrl.js, assets/js/templates/views/team.html
On a team page for which you are an admin, there will be a new form allowing you to make a new admin for that team.
/#/team/:id
=> Add admin to team

assets/js/directives/top_bar_directive.js, assets/js/templates/directives/top_bar_template.html
Created directive for top bar.
=> Added top bar directive.

assets/js/controllers/team_ctrl.js, assets/js/templates/directives/admin_module_template.html, assets/js/templates/views/team.html, assets/js/templates/views/user_create.html, assets/js/templates/views/user_profile.html
This updates the team and user views to a more consistent styling.  That doesn't mean they're pretty, just that they're consistent.
Note: there are some differences in the styling of forms on the team and user pages from those on the library and module pages.  I'm going to update the library and module pages in a separate commit.
Please review the team pages as both a student and admin, the user create page (#/admin/user/create) and your individual student profile (along with the edit page).
=> Style team and user pages

assets/js/directives/student_top_bar_directive.js, assets/js/templates/directives/student_top_bar_template.html
Make sure to check the "View Team" button takes you to the correct team.
=> Switched student top bar to use just links

assets/js/app.js, assets/js/services/auth_service.js
redirect to /#/login if not logged in
if logged in, app behavior should be normal
=> add angular auth

assets/js/controllers/user_view_ctrl.js, assets/js/directives/admin_sidebar_directive.js, assets/js/directives/student_sidebar_directive.js, assets/js/templates/directives/admin_sidebar_template.html, assets/js/templates/directives/student_sidebar_template.html, views/layout.ejs
Looks to whether user is student or admin, and shows appropriate side/top bars.
*** still needs admin top bar to be added
=> User permission controller

api/controllers/UserController.js
You should now be sent to the library page of your first team after login
please note that you may have to update your bootstrap file depending on if you've got a team which has a library or not
if not associated with a team with a library, you should be sent to your profile page
=> Redirect after login to Library

assets/js/controllers/team_ctrl.js, assets/js/templates/views/team.html
All admins should have (admin) besides their names.
=> (admin) on team page

assets/js/templates/directives/admin_sidebar_template.html, assets/js/templates/directives/student_sidebar_template.html
Module names are now clickable in sidebar and link to module view.
=> Module names are now clickable in sidebar and link to module view.

assets/js/controllers/user_creation_ctrl.js, assets/js/templates/views/user_create.html
As admin, go to /#/admin/user/create
This gives you a form to create new users. All fields are required (email in form [a-z]+\@[a-z]+\.[a-z]+, roughly).
After adding a user, you should see a list appear/update with these new users. Their names link to their profile pages. The remove button should remove them from the page and make a delete request so that they are gone from the database too.
=> add list of newly added users to admin create user page

assets/js/templates/views/team.html
swapped out the list for a table.
=> All remove user buttons in cohort view now line up

assets/js/app.js
So this is something of a stopgap that will probably need to be replaced because it's not very secure. The purpose is to prevent users who aren't admins from accessing admin routes, and from preventing users from accessing libraries that don't belong to one of their teams.
Concerns: there will be a moment when data is exposed. This could conceivably be fixed by using the "resolve" dealio on the angular routes. Or by passing data in headers. Or something.
I think we should consider merging this so that we have a sense of what pages any given user should be able to access. I don't think that this is the final solution.
=> Admin auth

assets/js/directives/admin_top_nav_directive.js, assets/js/templates/directives/admin_top_nav_template.html
logout button is removed on logout, dropdown bar works as intended, 'core' shows on sign in
=> Show core button

api/controllers/TeamController.js, api/services/coreLibrary.js
-Edited @spasiu 's work to communicate with front end
-Added associations between team and library
=> Clone core

assets/js/directives/admin_top_nav_directive.js, assets/js/directives/student_top_bar_directive.js, assets/js/services/auth_service.js, assets/js/services/bar_service.js, assets/js/templates/directives/admin_top_nav_template.html, assets/js/templates/directives/student_top_bar_template.html
Creates bar_service to aid the lovely top bar nav directives.
Will need to test as a student and as an admin (must be user to be an admin).
=> Service refactor

assets/js/directives/student_sidebar_directive.js
change query structure from params to use current user object to obtain library id.
=> Updating query structure for student sidebar.

assets/js/app.js, assets/js/controllers/header_ctrl.js, assets/js/controllers/lesson_ctrl.js, assets/js/controllers/library_ctrl.js, assets/js/controllers/module_ctrl.js, assets/js/controllers/sidebar_ctrl.js, assets/js/controllers/team_ctrl.js, assets/js/controllers/user_creation_ctrl.js, assets/js/controllers/user_ctrl.js, assets/js/controllers/user_view_ctrl.js
=> angular js controllers are uppercase

api/controllers/UserController.js, api/services/authService.js, api/services/githubStateService.js
Break into two additional services, stateService.js and authService.js
=> refactor UserController.js
